name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  publish_python:
    name: Publish Python Source Distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install twine

      - name: Get source distribution
        run: |
          python setup.py sdist

      - name: Publish to PyPI
        run: |
          python -m twine upload --non-interactive --verbose dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
